env:
  browser: true
  es6: true
extends:
  - "eslint:recommended"
  - "plugin:@typescript-eslint/recommended"
plugins:
  - "@typescript-eslint"
ignorePatterns:
  - "dist/"
overrides:
  - files: ["*.mjs"]
parserOptions:
  ecmaVersion: latest
  sourceType: module
  project: tsconfig.json
rules:
  no-throw-literal: [error]
  quotes: [error, double, { avoidEscape: true }]
  indent: [error, 4, { SwitchCase: 1 }]
  semi: [error, always]
  comma-dangle: [error, always-multiline]
  linebreak-style: [error, unix]
  "@typescript-eslint/no-unused-vars": [error, { varsIgnorePattern: "_", argsIgnorePattern: "_" }]
  "@typescript-eslint/no-inferrable-types": off
  "@typescript-eslint/no-explicit-any": off
  "@typescript-eslint/ban-ts-comment": off
